version: "3.9"
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: gossip
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
